In [6]:
import pandas as pd

df=pd.read_excel("IPL.xls")

In [16]:
matchs=df[(df["Bat_Second_15_ov_wkts_lost"]==6)&(df["Bat_Second_20_ov_score"]-df["Bat_Second_15_ov_score"]==33)]
matchs[['Match_Number','Date','Team_Batting_First','Team_Batting_Second']]

     Match_Number    Date Team_Batting_First Team_Batting_Second
301           302  May 11          Bangalore                Pune

In [18]:
matches_2 = df[(df["Bat_First_15_ov_wkts_lost"]==2)&(df["Bat_First_20_ov_score"]-df["Bat_First_15_ov_score"] < df["Bat_Second_20_ov_score"]-df["Bat_Second_15_ov_score"])]
matches_2[['Match_Number','Date','Team_Batting_First','Team_Batting_Second']]

     Match_Number    Date Team_Batting_First Team_Batting_Second
16             17  Apr 30              Delhi           Bangalore
51             52  May 26             Mumbai           Rajasthan
100           101  May 14          Rajasthan              Mumbai
180           181  Apr 11            Kolkata           Hyderabad
196           197  Apr 21             Punjab           Rajasthan
245           246  May 27          Bangalore              Mumbai
272           273  Apr 21          Rajasthan             Chennai
274           275  Apr 22             Mumbai              Punjab
281           282  Apr 28             Punjab             Chennai
291           292   May 5            Kolkata                Pune
324           325   Apr 6          Rajasthan               Delhi
336           337  Apr 13          Bangalore             Chennai
370           371   May 5               Pune           Rajasthan
382           383  May 13          Hyderabad              Mumbai
415           416  Apr 29          Rajasthan             Kolkata
440           441  May 19             Mumbai           Rajasthan
469           470  Apr 18              Delhi           Hyderabad
474           475  Apr 21          Rajasthan              Punjab
501           502  May 10            Chennai           Rajasthan
502           503  May 11          Hyderabad              Punjab